build:trusty:
  image: ubuntu:trusty
  stage: build
  script: 
    - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main" > /etc/apt/sources.list.d/toolchain.list
    - |
      echo "
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: SKS 1.1.6
      Comment: Hostname: keyserver.ubuntu.com

      mI0ESuBvRwEEAMi4cDba7xlKaaoXjO1n1HX8RKrkW+HEIl79nSOSJyvzysajs7zUow/OzCQp
      9NswqrDmNuH1+lPTTRNAGtK8r2ouq2rnXT1mTl23dpgHZ9spseR73s4ZBGw/ag4bpU5dNUSt
      vfmHhIjVCuiSpNn7cyy1JSSvSs3N2mxteKjXLBf7ABEBAAG0GkxhdW5jaHBhZCBUb29sY2hh
      aW4gYnVpbGRziLYEEwECACAFAkrgb0cCGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRAe
      k3eiup7yfzGKA/4xzUqNACSlB+k+DxFFHqkwKa/ziFiAlkLQyyhm+iqz80htRZr7Ls/ZRYZl
      0aSU56/hLe0V+TviJ1s8qdN2lamkKdXIAFfavA04nOnTzyIBJ82EAUT3Nh45skMxo4z4iZMN
      msyaQpNl/m/lNtOLhR64v5ZybofB2EWkMxUzX8D/FQ==
      =LcUQ
      -----END PGP PUBLIC KEY BLOCK-----" | apt-key add -
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake3 gcc-7 g++-7 libstdc++6 build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev libssl-dev pkg-config
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f .ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f .ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-7 -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 -DWITH_RABBITMQ=OFF ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:xenial:
  image: ubuntu:xenial
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f .ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f .ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:bionic:
  image: ubuntu:bionic
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f .ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f .ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:jessie:
  image: debian:jessie
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f .ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f .ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:stretch:
  image: debian:stretch
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f .ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f .ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:nagios:trusty:
  image: ubuntu:trusty
  stage: build
  script: 
    - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main" > /etc/apt/sources.list.d/toolchain.list
    - |
      echo "
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: SKS 1.1.6
      Comment: Hostname: keyserver.ubuntu.com

      mI0ESuBvRwEEAMi4cDba7xlKaaoXjO1n1HX8RKrkW+HEIl79nSOSJyvzysajs7zUow/OzCQp
      9NswqrDmNuH1+lPTTRNAGtK8r2ouq2rnXT1mTl23dpgHZ9spseR73s4ZBGw/ag4bpU5dNUSt
      vfmHhIjVCuiSpNn7cyy1JSSvSs3N2mxteKjXLBf7ABEBAAG0GkxhdW5jaHBhZCBUb29sY2hh
      aW4gYnVpbGRziLYEEwECACAFAkrgb0cCGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRAe
      k3eiup7yfzGKA/4xzUqNACSlB+k+DxFFHqkwKa/ziFiAlkLQyyhm+iqz80htRZr7Ls/ZRYZl
      0aSU56/hLe0V+TviJ1s8qdN2lamkKdXIAFfavA04nOnTzyIBJ82EAUT3Nh45skMxo4z4iZMN
      msyaQpNl/m/lNtOLhR64v5ZybofB2EWkMxUzX8D/FQ==
      =LcUQ
      -----END PGP PUBLIC KEY BLOCK-----" | apt-key add -
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake3 gcc-7 g++-7 libstdc++6 build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f .ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-7 -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 -DWITH_RABBITMQ=OFF -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:nagios:xenial:
  image: ubuntu:xenial
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f .ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:nagios:bionic:
  image: ubuntu:bionic
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f .ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:nagios:jessie:
  image: debian:jessie
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f .ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

build:nagios:stretch:
  image: debian:stretch
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f .ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    paths:
      - libstatusengine.so

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
