build:trusty:
  image: ubuntu:trusty
  stage: build
  script: 
    - apt-get update && apt-get install -y software-properties-common 
    - add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - apt-get update && apt-get -y install cmake3 gcc-7 g++-7 libstdc++6 build-essential automake gperf help2man libtool libglib2.0-dev libgearman-dev wget tar
    - useradd -d /opt/naemon -m -s /bin/bash --system naemon
    - >
      set -e &&
      OLDWD="$(pwd)" &&
      cd /tmp/ &&
      wget https://github.com/naemon/naemon-core/archive/v1.0.6.tar.gz &&
      tar xfv v1.0.6.tar.gz && cd naemon-core-1.0.6/ &&
      ./autogen.sh --prefix=/opt/naemon --with-naemon-user=naemon --with-naemon-group=naemon --with-pluginsdir=/usr/lib/nagios/plugins &&
      make all -j5 &&
      make install &&
      mkdir -p /opt/naemon/var/ /opt/naemon/var/cache/naemon /opt/naemon/var/spool/checkresults &&
      chown naemon:naemon /opt/naemon/var -R &&
      mkdir -p /usr/local/lib/pkgconfig &&
      ln -s /opt/naemon/lib/pkgconfig/naemon.pc /usr/local/lib/pkgconfig/naemon.pc &&
      cd "${OLDWD}"
    - >
      mkdir build &&
      cd build &&
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-7 -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 .. &&
      make -j5
  artifacts:
    paths:
      - build/libstatusengine.so


build:xenial:
  image: ubuntu:xenial
  stage: build
  script:
    - apt-get update && apt-get -y install cmake gcc g++ build-essential automake gperf help2man libtool libglib2.0-dev libgearman-dev wget tar
    - useradd -d /opt/naemon -m -s /bin/bash --system naemon
    - >
      set -e &&
      OLDWD="$(pwd)" &&
      cd /tmp/ &&
      wget https://github.com/naemon/naemon-core/archive/v1.0.6.tar.gz &&
      tar xfv v1.0.6.tar.gz && cd naemon-core-1.0.6/ &&
      ./autogen.sh --prefix=/opt/naemon --with-naemon-user=naemon --with-naemon-group=naemon --with-pluginsdir=/usr/lib/nagios/plugins &&
      make all -j5 &&
      make install &&
      mkdir -p /opt/naemon/var/ /opt/naemon/var/cache/naemon /opt/naemon/var/spool/checkresults &&
      chown naemon:naemon /opt/naemon/var -R &&
      mkdir -p /usr/local/lib/pkgconfig &&
      ln -s /opt/naemon/lib/pkgconfig/naemon.pc /usr/local/lib/pkgconfig/naemon.pc &&
      cd "${OLDWD}"
    - >
      mkdir build &&
      cd build &&
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ .. &&
      make -j5
  artifacts:
    paths:
      - build/libstatusengine.so


build:stretch:
  image: debian:stretch
  stage: build
  script:
    - apt-get update && apt-get -y install cmake gcc g++ build-essential automake gperf help2man libtool libglib2.0-dev libgearman-dev wget tar
    - useradd -d /opt/naemon -m -s /bin/bash --system naemon
    - >
      set -e &&
      OLDWD="$(pwd)" &&
      cd /tmp/ &&
      wget https://github.com/naemon/naemon-core/archive/v1.0.6.tar.gz &&
      tar xfv v1.0.6.tar.gz && cd naemon-core-1.0.6/ &&
      ./autogen.sh --prefix=/opt/naemon --with-naemon-user=naemon --with-naemon-group=naemon --with-pluginsdir=/usr/lib/nagios/plugins &&
      make all -j5 &&
      make install &&
      mkdir -p /opt/naemon/var/ /opt/naemon/var/cache/naemon /opt/naemon/var/spool/checkresults &&
      chown naemon:naemon /opt/naemon/var -R &&
      mkdir -p /usr/local/lib/pkgconfig &&
      ln -s /opt/naemon/lib/pkgconfig/naemon.pc /usr/local/lib/pkgconfig/naemon.pc &&
      cd "${OLDWD}"
    - >
      mkdir build &&
      cd build &&
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ .. &&
      make -j5
  artifacts:
    paths:
      - build/libstatusengine.so

# run tests using the binary built before
#test:
#  stage: test
#  script:
#    - ./runmytests.sh
