build:trusty:
  image: ubuntu:trusty
  stage: build
  script: 
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake3 gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev libssl-dev pkg-config librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f devtools/ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f devtools/ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:xenial:
  image: ubuntu:xenial
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f devtools/ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f devtools/ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:bionic:
  image: ubuntu:bionic
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f devtools/ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f devtools/ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:jessie:
  image: debian:jessie
  stage: build
  script:
    - echo "deb http://ftp.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y -t jessie-backports install cmake gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f devtools/ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f devtools/ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:stretch:
  image: debian:stretch
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libglib2.0-dev libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /usr/local/lib/pkgconfig /opt/naemon/include
      ln -s $(readlink -f devtools/ci/naemon) /opt/naemon/include/naemon
      ln -s $(readlink -f devtools/ci/naemon.pc) /usr/local/lib/pkgconfig/naemon.pc
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:nagios:trusty:
  image: ubuntu:trusty
  stage: build
  script: 
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake3 gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev libglib2.0-dev librabbitmq-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f devtools/ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:nagios:xenial:
  image: ubuntu:xenial
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f devtools/ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:nagios:bionic:
  image: ubuntu:bionic
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f devtools/ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:nagios:jessie:
  image: debian:jessie
  stage: build
  script:
    - echo "deb http://ftp.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y -t jessie-backports install cmake gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f devtools/ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE

build:nagios:stretch:
  image: debian:stretch
  stage: build
  script:
    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y install cmake gcc g++ build-essential libgearman-dev uuid-dev libicu-dev libjson-c-dev pkg-config libssl-dev librabbitmq-dev libglib2.0-dev
    - |
      set -e
      mkdir -p /opt/nagios/include
      ln -s $(readlink -f devtools/ci/nagios) /opt/nagios/include/nagios
    - |
      mkdir build
      cd build
      cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DBUILD_NAGIOS=ON -DNAGIOS_INCLUDE_DIR=/opt/nagios/include ..
      make -j5
      mv libstatusengine.so ..
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - libstatusengine.so
      - README.md
      - VERSION
      - LICENSE
